-- By D4KiR
-- REALMS FROZEN: the cata status page no longer exists, this data is kept as it was
local _, D4 = ...
if D4:GetWoWBuild() ~= "CATA" then return end
D4:AddRealmData(
    function(realms, region, regions)
        if region == regions["US"] then
            if GetLocale() == "enUS" then
                realms["Angerforge"] = "US West"
                realms["Arugal"] = "Oceanic"
                realms["Ashkandi"] = "US East"
                realms["Atiesh"] = "US West"
                realms["Azuresong"] = "US West"
                realms["Benediction"] = "US East"
                realms["Bloodsail Buccaneers"] = "US East"
                realms["Earthfury"] = "US East"
                realms["Eranikus"] = "US East"
                realms["Faerlina"] = "US East"
                realms["Grobbulus"] = "US West"
                realms["Maladath"] = "US East"
                realms["Mankrik"] = "US East"
                realms["Myzrael"] = "US West"
                realms["Old Blanchy"] = "US West"
                realms["Pagle"] = "US East"
                realms["Remulos"] = "Oceanic"
                realms["Skyfury"] = "US West"
                realms["Sulfuras"] = "US East"
                realms["Westfall"] = "US East"
                realms["Whitemane"] = "US West"
                realms["Windseeker"] = "US East"
                realms["Yojamba"] = "Oceanic"
            elseif GetLocale() == "deDE" then
                realms["Angerforge"] = "USA West"
                realms["Arugal"] = "Ozeanisch"
                realms["Ashkandi"] = "USA Ost"
                realms["Atiesh"] = "USA West"
                realms["Azuresong"] = "USA West"
                realms["Benediction"] = "USA Ost"
                realms["Bloodsail Buccaneers"] = "USA Ost"
                realms["Earthfury"] = "USA Ost"
                realms["Eranikus"] = "USA Ost"
                realms["Faerlina"] = "USA Ost"
                realms["Grobbulus"] = "USA West"
                realms["Maladath"] = "USA Ost"
                realms["Mankrik"] = "USA Ost"
                realms["Myzrael"] = "USA West"
                realms["Old Blanchy"] = "USA West"
                realms["Pagle"] = "USA Ost"
                realms["Remulos"] = "Ozeanisch"
                realms["Skyfury"] = "USA West"
                realms["Sulfuras"] = "USA Ost"
                realms["Westfall"] = "USA Ost"
                realms["Whitemane"] = "USA West"
                realms["Windseeker"] = "USA Ost"
                realms["Yojamba"] = "Ozeanisch"
            elseif GetLocale() == "koKR" then
                realms["Angerforge"] = "미국 서부"
                realms["Arugal"] = "오세아니아"
                realms["Ashkandi"] = "미국 동부"
                realms["Atiesh"] = "미국 서부"
                realms["Azuresong"] = "미국 서부"
                realms["Benediction"] = "미국 동부"
                realms["Bloodsail Buccaneers"] = "미국 동부"
                realms["Earthfury"] = "미국 동부"
                realms["Eranikus"] = "미국 동부"
                realms["Faerlina"] = "미국 동부"
                realms["Grobbulus"] = "미국 서부"
                realms["Maladath"] = "미국 동부"
                realms["Mankrik"] = "미국 동부"
                realms["Myzrael"] = "미국 서부"
                realms["Old Blanchy"] = "미국 서부"
                realms["Pagle"] = "미국 동부"
                realms["Remulos"] = "오세아니아"
                realms["Skyfury"] = "미국 서부"
                realms["Sulfuras"] = "미국 동부"
                realms["Westfall"] = "미국 동부"
                realms["Whitemane"] = "미국 서부"
                realms["Windseeker"] = "미국 동부"
                realms["Yojamba"] = "오세아니아"
            elseif GetLocale() == "zhTW" then
                realms["伊蘭尼庫斯"] = "美東"
                realms["大地之怒"] = "美東"
                realms["天怒"] = "美西"
                realms["安格弗"] = "美西"
                realms["密斯賴爾"] = "美西"
                realms["尤亞姆巴"] = "大洋洲"
                realms["帕格"] = "美東"
                realms["懷特邁恩"] = "美西"
                realms["曼寇里克"] = "美東"
                realms["瑪拉達斯"] = "美東"
                realms["碧空之歌"] = "美西"
                realms["祈福"] = "美東"
                realms["老馬布蘭契"] = "美西"
                realms["葛羅巴斯"] = "美西"
                realms["薩弗拉斯"] = "美東"
                realms["血帆海盜"] = "美東"
                realms["西部荒野"] = "美東"
                realms["費琳娜"] = "美東"
                realms["逐風者"] = "美東"
                realms["阿什坎迪"] = "美東"
                realms["阿泰絲"] = "美西"
                realms["阿魯高"] = "大洋洲"
                realms["雷姆洛斯"] = "大洋洲"
            end
        elseif region == regions["EU"] then
            if GetLocale() == "enUS" then
                realms["Amnennar"] = "French"
                realms["Ashbringer"] = "English"
                realms["Auberdine"] = "French"
                realms["Chromie"] = "Russian"
                realms["Earthshaker"] = "English"
                realms["Everlook"] = "German"
                realms["Firemaw"] = "English"
                realms["Flamegor"] = "Russian"
                realms["Gehennas"] = "English"
                realms["Giantstalker"] = "English"
                realms["Golemagg"] = "English"
                realms["Hydraxian Waterlords"] = "English"
                realms["Jin'do"] = "English"
                realms["Lakeshire"] = "German"
                realms["Mandokir"] = "Spanish"
                realms["Mirage Raceway"] = "English"
                realms["Mograine"] = "English"
                realms["Nethergarde Keep"] = "English"
                realms["Patchwerk"] = "German"
                realms["Pyrewood Village"] = "English"
                realms["Razorfen"] = "German"
                realms["Sulfuron"] = "French"
                realms["Thekal"] = "English"
                realms["Transcendence"] = "German"
                realms["Venoxis"] = "German"
            elseif GetLocale() == "deDE" then
                realms["Amnennar"] = "Französisch"
                realms["Ashbringer"] = "Englisch"
                realms["Auberdine"] = "Französisch"
                realms["Earthshaker"] = "Englisch"
                realms["Everlook"] = "Deutsch"
                realms["Firemaw"] = "Englisch"
                realms["Gehennas"] = "Englisch"
                realms["Giantstalker"] = "Englisch"
                realms["Golemagg"] = "Englisch"
                realms["Hydraxian Waterlords"] = "Englisch"
                realms["Jin'do"] = "Englisch"
                realms["Lakeshire"] = "Deutsch"
                realms["Mandokir"] = "Spanisch"
                realms["Mirage Raceway"] = "Englisch"
                realms["Mograine"] = "Englisch"
                realms["Nethergarde Keep"] = "Englisch"
                realms["Patchwerk"] = "Deutsch"
                realms["Pyrewood Village"] = "Englisch"
                realms["Razorfen"] = "Deutsch"
                realms["Sulfuron"] = "Französisch"
                realms["Thekal"] = "Englisch"
                realms["Transcendence"] = "Deutsch"
                realms["Venoxis"] = "Deutsch"
                realms["Пламегор"] = "Russisch"
                realms["Хроми"] = "Russisch"
            elseif GetLocale() == "koKR" then
                realms["Amnennar"] = "프랑스어"
                realms["Ashbringer"] = "영어"
                realms["Auberdine"] = "프랑스어"
                realms["Chromie"] = "러시아어"
                realms["Earthshaker"] = "영어"
                realms["Everlook"] = "독일어"
                realms["Firemaw"] = "영어"
                realms["Flamegor"] = "러시아어"
                realms["Gehennas"] = "영어"
                realms["Giantstalker"] = "영어"
                realms["Golemagg"] = "영어"
                realms["Hydraxian Waterlords"] = "영어"
                realms["Jin'do"] = "영어"
                realms["Lakeshire"] = "독일어"
                realms["Mandokir"] = "스페인어"
                realms["Mirage Raceway"] = "영어"
                realms["Mograine"] = "영어"
                realms["Nethergarde Keep"] = "영어"
                realms["Patchwerk"] = "독일어"
                realms["Pyrewood Village"] = "영어"
                realms["Razorfen"] = "독일어"
                realms["Sulfuron"] = "프랑스어"
                realms["Thekal"] = "영어"
                realms["Transcendence"] = "독일어"
                realms["Venoxis"] = "독일어"
            elseif GetLocale() == "zhTW" then
                realms["亞門納爾"] = "法國"
                realms["克羅米"] = "俄羅斯"
                realms["剃刀高地"] = "德國"
                realms["古雷曼格"] = "英國"
                realms["基赫納斯"] = "英國"
                realms["塞卡爾"] = "英國"
                realms["奧伯丁"] = "法國"
                realms["守望堡"] = "英國"
                realms["巨人巡者"] = "英國"
                realms["弗萊格爾"] = "俄羅斯"
                realms["曼多基爾"] = "西班牙"
                realms["永望鎮"] = "德國"
                realms["沙漠賽道"] = "英國"
                realms["海達希亞水元素"] = "英國"
                realms["湖畔鎮"] = "德國"
                realms["溫諾希斯"] = "德國"
                realms["灰燼使者"] = "英國"
                realms["焚木村"] = "英國"
                realms["縫補者"] = "德國"
                realms["莫格萊尼"] = "英國"
                realms["薩弗隆"] = "法國"
                realms["費爾默"] = "英國"
                realms["超凡入聖"] = "德國"
                realms["金度"] = "英國"
                realms["震地者"] = "英國"
            end
        elseif region == regions["KR"] then
            if GetLocale() == "enUS" then
                realms["Frostmourne"] = "Korea"
                realms["Iceblood"] = "Korea"
                realms["Lokholar"] = "Korea"
                realms["Ragnaros"] = "Korea"
                realms["Shimmering Flats"] = "Korea"
            elseif GetLocale() == "deDE" then
                realms["Frostmourne"] = "Korea"
                realms["Iceblood"] = "Korea"
                realms["Lokholar"] = "Korea"
                realms["Ragnaros"] = "Korea"
                realms["Shimmering Flats"] = "Korea"
            elseif GetLocale() == "koKR" then
                realms["라그나로스"] = "한국"
                realms["로크홀라"] = "한국"
                realms["서리한"] = "한국"
                realms["소금 평원"] = "한국"
                realms["얼음피"] = "한국"
            elseif GetLocale() == "zhTW" then
                realms["冰血"] = "韓國"
                realms["拉格納羅斯"] = "韓國"
                realms["洛克霍拉"] = "韓國"
                realms["閃光平原"] = "韓國"
                realms["霜之哀傷"] = "韓國"
            end
        elseif region == regions["TW"] then
            if GetLocale() == "enUS" then
                realms["Arathi Basin"] = "Global"
                realms["Golemagg"] = "Global"
                realms["Ivus"] = "Taiwan"
                realms["Maraudon"] = "Taiwan"
                realms["Murloc"] = "Global"
                realms["Windseeker"] = "Global"
                realms["Wushoolay"] = "Taiwan"
                realms["Zeliek"] = "Global"
            elseif GetLocale() == "deDE" then
                realms["Arathi Basin"] = "Global"
                realms["Golemagg"] = "Global"
                realms["Murloc"] = "Global"
                realms["Windseeker"] = "Global"
                realms["伊弗斯"] = "Taiwan"
                realms["札里克"] = "Global"
                realms["烏蘇雷"] = "Taiwan"
                realms["瑪拉頓"] = "Taiwan"
            elseif GetLocale() == "koKR" then
                realms["Arathi Basin"] = "글로벌"
                realms["Golemagg"] = "글로벌"
                realms["Ivus"] = "대만"
                realms["Maraudon"] = "대만"
                realms["Murloc"] = "글로벌"
                realms["Windseeker"] = "글로벌"
                realms["Wushoolay"] = "대만"
                realms["Zeliek"] = "글로벌"
            elseif GetLocale() == "zhTW" then
                realms["伊弗斯"] = "台灣"
                realms["古雷曼格"] = "全球"
                realms["札里克"] = "全球"
                realms["烏蘇雷"] = "台灣"
                realms["瑪拉頓"] = "台灣"
                realms["逐風者"] = "全球"
                realms["阿拉希盆地"] = "全球"
                realms["魚人"] = "全球"
            end
        else
            D4:MissingRealmRegion(region)
        end
    end
)
